[workspace]
name = "test-workspace"
description = "A C++ workspace"

# Projects in format: name:path:is_startup_project
projects = [
  "lib-a:lib-a:true",
  "lib-b:lib-b:false",
  "app-main:app-main:false"
]

# Dependencies are stored in project-specific cforge.toml files
