/**
 * @file test_runner.cpp
 * @brief Implementation of the test runner for cforge's testing system
 */

#include "core/test_runner.hpp"
#include "cforge/log.hpp"
#include "core/types.h"
#include "core/process_utils.hpp"
#include "core/test_adapters.hpp"
#include "core/workspace.hpp"

#include <algorithm>
#include <fstream>
#include <regex>
#include <sstream>

namespace cforge {

namespace fs = std::filesystem;

// Helper to convert path to CMake format (forward slashes)
static std::string to_cmake_path(const fs::path &path) {
  std::string str = path.string();
  std::replace(str.begin(), str.end(), '\\', '/');
  return str;
}

// Strip ANSI escape sequences so colored test output still parses cleanly.
static std::string strip_ansi(const std::string &input) {
  static const std::regex ansi_re("\x1b\\[[0-9;]*[A-Za-z]");
  return std::regex_replace(input, ansi_re, "");
}

// Read a file fully into a string. Empty string on failure.
static std::string read_file_to_string(const fs::path &path) {
  std::ifstream in(path);
  if (!in) return {};
  std::ostringstream oss;
  oss << in.rdbuf();
  return oss.str();
}

// Bounded recursive search for an executable named like the target. Walks the
// build dir up to a moderate depth so it works with single- and multi-config
// generators (Ninja vs MSBuild) without hardcoded paths.
static fs::path find_executable_in_dir(const fs::path &build_dir,
                                       const std::vector<std::string> &name_candidates) {
  if (!fs::exists(build_dir)) return {};

  std::error_code ec;
  for (auto it = fs::recursive_directory_iterator(
                  build_dir, fs::directory_options::skip_permission_denied, ec);
       !ec && it != fs::recursive_directory_iterator(); it.increment(ec)) {
    if (it.depth() > 6) {
      it.disable_recursion_pending();
      continue;
    }
    if (!it->is_regular_file(ec)) continue;
    const auto &p = it->path();
    auto stem = p.stem().string();
    auto filename = p.filename().string();
    auto ext = p.extension().string();

#ifdef _WIN32
    // Only consider .exe on Windows
    if (ext != ".exe") continue;
#else
    // On POSIX, accept extension-less files; skip generated CMake junk
    if (!ext.empty() && ext != ".out") continue;
    if (filename.find("CMake") != std::string::npos) continue;
#endif

    for (const auto &cand : name_candidates) {
      if (stem == cand || filename == cand) {
        return p;
      }
    }
  }
  return {};
}

// Embedded copy of tests/test_framework.h. Single source of truth lives in the
// runtime header file; this string is its mirror, used to drop the header into
// the build dir at generate-time so users don't need to copy it themselves.
static const char *get_builtin_test_framework_header() {
  // NOTE: Keep in sync with tests/test_framework.h
  return R"CFTF(/**
 * @file test_framework.h
 * @brief Zero-config, auto-registering test framework for cforge projects
 *
 * Generated by cforge — do not edit. Update tests/test_framework.h in cforge
 * source if you want to change the canonical version.
 */

#ifndef CFORGE_TEST_FRAMEWORK_H
#define CFORGE_TEST_FRAMEWORK_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__cplusplus)
#elif defined(_MSC_VER)
  #pragma section(".CRT$XCU", read)
  #ifdef _WIN64
    #define CF_INCLUDE_PREFIX ""
  #else
    #define CF_INCLUDE_PREFIX "_"
  #endif
  #define CF_CTOR_(fn, line)                                                    \
      static void fn(void);                                                     \
      __pragma(section(".CRT$XCU",read))                                        \
      __declspec(allocate(".CRT$XCU")) void (*fn##_ptr_##line)(void) = fn;      \
      __pragma(comment(linker,"/include:" CF_INCLUDE_PREFIX #fn "_ptr_" #line)) \
      static void fn(void)
  #define CF_CTOR_X(fn, line) CF_CTOR_(fn, line)
  #define CF_CTOR(fn) CF_CTOR_X(fn, __LINE__)
#elif defined(__GNUC__) || defined(__clang__)
  #define CF_CTOR(fn) static void __attribute__((constructor)) fn(void)
#else
  #error "Unsupported compiler: please use MSVC, GCC, or Clang"
#endif

#if defined(_WIN32)
  #define CF_SELECTANY __declspec(selectany)
#elif defined(_MSC_VER)
  #define CF_SELECTANY __declspec(selectany)
#elif defined(__GNUC__) || defined(__clang__)
  #define CF_SELECTANY __attribute__((weak))
#else
  #define CF_SELECTANY
#endif

#if defined(__GNUC__) || defined(__clang__)
  #define CF_MAYBE_UNUSED __attribute__((unused))
#else
  #define CF_MAYBE_UNUSED
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef int (*cf_test_func_t)(void);
typedef struct cf_test_node {
    const char* name;
    cf_test_func_t func;
    struct cf_test_node* next;
} cf_test_node_t;

CF_SELECTANY cf_test_node_t* cf_test_head_ = (cf_test_node_t*)0;
CF_SELECTANY int cf_color_enabled_ = 1;

static CF_MAYBE_UNUSED void cf_test_register_node_(cf_test_node_t* node) {
    node->next = cf_test_head_;
    cf_test_head_ = node;
}

static CF_MAYBE_UNUSED void cf_register_test(const char* name, cf_test_func_t func) {
    cf_test_node_t* node = (cf_test_node_t*)malloc(sizeof(cf_test_node_t));
    if (!node) return;
    node->name = name;
    node->func = func;
    cf_test_register_node_(node);
}

static CF_MAYBE_UNUSED const char* cf_red_(void)    { return cf_color_enabled_ ? "\x1b[31m" : ""; }
static CF_MAYBE_UNUSED const char* cf_green_(void)  { return cf_color_enabled_ ? "\x1b[32m" : ""; }
static CF_MAYBE_UNUSED const char* cf_yellow_(void) { return cf_color_enabled_ ? "\x1b[33m" : ""; }
static CF_MAYBE_UNUSED const char* cf_cyan_(void)   { return cf_color_enabled_ ? "\x1b[36m" : ""; }
static CF_MAYBE_UNUSED const char* cf_dim_(void)    { return cf_color_enabled_ ? "\x1b[2m"  : ""; }
static CF_MAYBE_UNUSED const char* cf_reset_(void)  { return cf_color_enabled_ ? "\x1b[0m"  : ""; }

#ifdef __cplusplus
}
#endif

#define CF_COLOR_RED     "\x1b[31m"
#define CF_COLOR_GREEN   "\x1b[32m"
#define CF_COLOR_YELLOW  "\x1b[33m"
#define CF_COLOR_CYAN    "\x1b[36m"
#define CF_COLOR_RESET   "\x1b[0m"

#if defined(_WIN32)
  #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
  #endif
  #include <windows.h>
  static CF_MAYBE_UNUSED void cf_enable_vt_(void) {
      HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
      DWORD mode = 0;
      if (h == INVALID_HANDLE_VALUE || h == NULL) { cf_color_enabled_ = 0; return; }
      if (!GetConsoleMode(h, &mode)) { return; }
      if (!SetConsoleMode(h, mode | 0x0004)) { cf_color_enabled_ = 0; }
  }
#else
  static CF_MAYBE_UNUSED void cf_enable_vt_(void) { }
#endif

#define cf_assert(expr)                                                         \
    do {                                                                        \
        if (!(expr)) {                                                          \
            fprintf(stderr, "%sAssertion failed: %s at %s:%d%s\n",              \
                cf_red_(), #expr, __FILE__, __LINE__, cf_reset_());             \
            return 1;                                                           \
        }                                                                       \
    } while (0)

#define cf_assert_eq(expected, actual)                                          \
    do {                                                                        \
        if ((expected) != (actual)) {                                           \
            fprintf(stderr, "%sAssertion failed: %s == %s at %s:%d%s\n",        \
                cf_red_(), #expected, #actual, __FILE__, __LINE__, cf_reset_());\
            return 1;                                                           \
        }                                                                       \
    } while (0)

#define cf_assert_ne(a, b)                                                      \
    do {                                                                        \
        if ((a) == (b)) {                                                       \
            fprintf(stderr, "%sAssertion failed: %s != %s at %s:%d%s\n",        \
                cf_red_(), #a, #b, __FILE__, __LINE__, cf_reset_());            \
            return 1;                                                           \
        }                                                                       \
    } while (0)

#define cf_assert_null(ptr)                                                     \
    do {                                                                        \
        if ((ptr) != NULL) {                                                    \
            fprintf(stderr, "%sAssertion failed: %s is not null at %s:%d%s\n",  \
                cf_red_(), #ptr, __FILE__, __LINE__, cf_reset_());              \
            return 1;                                                           \
        }                                                                       \
    } while (0)

#define cf_assert_not_null(ptr)                                                 \
    do {                                                                        \
        if ((ptr) == NULL) {                                                    \
            fprintf(stderr, "%sAssertion failed: %s is null at %s:%d%s\n",      \
                cf_red_(), #ptr, __FILE__, __LINE__, cf_reset_());              \
            return 1;                                                           \
        }                                                                       \
    } while (0)

#define test_assert(expr) cf_assert(expr)

static CF_MAYBE_UNUSED int cf_glob_match_(const char* pat, const char* s) {
    while (*pat && *s) {
        if (*pat == '*') {
            while (*pat == '*') pat++;
            if (*pat == 0) return 1;
            while (*s) {
                if (cf_glob_match_(pat, s)) return 1;
                s++;
            }
            return 0;
        } else if (*pat == '?' || *pat == *s) {
            pat++; s++;
        } else {
            return 0;
        }
    }
    while (*pat == '*') pat++;
    return *pat == 0 && *s == 0;
}

#define CF_CONCAT_(a, b) a##b
#define CF_CONCAT(a, b) CF_CONCAT_(a, b)
#define CF_UNIQUE(prefix) CF_CONCAT(prefix, __LINE__)

#ifdef __cplusplus
namespace cf_test_internal {
struct Registrar {
    cf_test_node_t node;
    Registrar(const char* name, cf_test_func_t fn) {
        node.name = name;
        node.func = fn;
        node.next = nullptr;
        cf_test_register_node_(&node);
    }
};
}
#define CF_TEST1(name)                                                          \
    static int name(void);                                                      \
    static ::cf_test_internal::Registrar CF_UNIQUE(cf_reg_)(#name, name);       \
    static int name(void)
#define CF_TEST2(suite, name)                                                   \
    static int CF_CONCAT(suite, CF_CONCAT(_, name))(void);                      \
    static ::cf_test_internal::Registrar CF_UNIQUE(cf_reg_)(                    \
        #suite "." #name, CF_CONCAT(suite, CF_CONCAT(_, name)));                \
    static int CF_CONCAT(suite, CF_CONCAT(_, name))(void)
#else
#define CF_TEST1(name)                                                          \
    static int name(void);                                                      \
    static cf_test_node_t CF_CONCAT(cf_node_, name) = { #name, name, 0 };       \
    CF_CTOR(CF_CONCAT(cf_reg_, name)) {                                         \
        cf_test_register_node_(&CF_CONCAT(cf_node_, name));                     \
    }                                                                           \
    static int name(void)
#define CF_TEST2(suite, name)                                                   \
    static int CF_CONCAT(suite, CF_CONCAT(_, name))(void);                      \
    static cf_test_node_t                                                       \
        CF_CONCAT(cf_node_, CF_CONCAT(suite, CF_CONCAT(_, name))) = {           \
            #suite "." #name,                                                   \
            CF_CONCAT(suite, CF_CONCAT(_, name)), 0 };                          \
    CF_CTOR(CF_CONCAT(cf_reg_, CF_CONCAT(suite, CF_CONCAT(_, name)))) {         \
        cf_test_register_node_(                                                 \
            &CF_CONCAT(cf_node_, CF_CONCAT(suite, CF_CONCAT(_, name))));        \
    }                                                                           \
    static int CF_CONCAT(suite, CF_CONCAT(_, name))(void)
#endif

#define CF_EXPAND(x) x
#define CF_GET_MACRO(_1, _2, NAME, ...) NAME
#define CF_TEST_CHOOSER(...) CF_EXPAND(CF_GET_MACRO(__VA_ARGS__, CF_TEST2, CF_TEST1))
#define TEST(...) CF_EXPAND(CF_TEST_CHOOSER(__VA_ARGS__)(__VA_ARGS__))

#ifdef __cplusplus
extern "C" {
#endif

static CF_MAYBE_UNUSED cf_test_node_t* cf_test_collect_in_order_(int* out_count) {
    cf_test_node_t* prev = (cf_test_node_t*)0;
    cf_test_node_t* curr = cf_test_head_;
    int count = 0;
    while (curr) {
        cf_test_node_t* next = curr->next;
        curr->next = prev;
        prev = curr;
        curr = next;
        count++;
    }
    cf_test_head_ = prev;
    if (out_count) *out_count = count;
    return prev;
}

static CF_MAYBE_UNUSED int cf_filter_matches_(const char* name,
                                              const char* const* filters, int filter_count) {
    int i; size_t flen;
    if (filter_count <= 0) return 1;
    for (i = 0; i < filter_count; i++) {
        const char* f = filters[i];
        if (!f) continue;
        if (cf_glob_match_(f, name)) return 1;
        if (strchr(f, '*') == 0 && strchr(f, '?') == 0) {
            if (strcmp(f, name) == 0) return 1;
            flen = strlen(f);
            if (strncmp(f, name, flen) == 0 && name[flen] == '.') return 1;
            if (strstr(name, f) != 0) return 1;
        }
    }
    return 0;
}

static CF_MAYBE_UNUSED int cf_run_tests(int argc, char** argv) {
    const char* filters[64];
    int filter_count = 0;
    int list_only = 0;
    int verbose = 0;
    int i;
    int total = 0;
    int passed = 0, failed = 0, skipped = 0;
    cf_test_node_t* head;
    cf_test_node_t* n;

    cf_enable_vt_();

    for (i = 1; i < argc; i++) {
        const char* a = argv[i];
        if (strcmp(a, "--list") == 0) {
            list_only = 1;
        } else if (strcmp(a, "-v") == 0 || strcmp(a, "--verbose") == 0) {
            verbose = 1;
        } else if (strcmp(a, "--no-color") == 0) {
            cf_color_enabled_ = 0;
        } else if (strcmp(a, "-f") == 0 || strcmp(a, "--filter") == 0) {
            if (i + 1 < argc && filter_count < 64) {
                filters[filter_count++] = argv[++i];
            }
        } else if (a[0] != '-') {
            if (filter_count < 64) filters[filter_count++] = a;
        }
    }

    head = cf_test_collect_in_order_(&total);

    if (list_only) {
        for (n = head; n != 0; n = n->next) {
            if (cf_filter_matches_(n->name, filters, filter_count)) {
                printf("%s\n", n->name);
            }
        }
        fflush(stdout);
        return 0;
    }

    printf("\n");
    for (n = head; n != 0; n = n->next) {
        int rc;
        if (!cf_filter_matches_(n->name, filters, filter_count)) {
            if (verbose) {
                printf("%s[SKIP]%s %s\n", cf_yellow_(), cf_reset_(), n->name);
            }
            skipped++;
            continue;
        }
        printf("%s[RUN]%s %s\n", cf_cyan_(), cf_reset_(), n->name);
        fflush(stdout);
        rc = n->func ? n->func() : 1;
        if (rc == 0) {
            printf("%s[PASS]%s %s\n", cf_green_(), cf_reset_(), n->name);
            passed++;
        } else {
            printf("%s[FAIL]%s %s\n", cf_red_(), cf_reset_(), n->name);
            failed++;
        }
        fflush(stdout);
    }

    printf("\n==============================\n");
    if (failed == 0) {
        printf("%sAll %d tests passed%s\n", cf_green_(), passed, cf_reset_());
    } else {
        printf("%s%d of %d tests failed%s\n",
               cf_red_(), failed, passed + failed, cf_reset_());
    }
    if (skipped && verbose) {
        printf("%s%d skipped%s\n", cf_dim_(), skipped, cf_reset_());
    }
    printf("==============================\n");
    fflush(stdout);

    return failed > 0 ? 1 : 0;
}

static CF_MAYBE_UNUSED int cf_run_tests_default(void) { return cf_run_tests(0, (char**)0); }

#ifdef __cplusplus
}
#endif

#endif
)CFTF";
}

// ============================================================================
// Constructor / Destructor
// ============================================================================

test_runner::test_runner(const fs::path &project_dir, const toml_reader &config)
    : m_project_dir(project_dir), m_project_config(config) {}

test_runner::~test_runner() = default;

// ============================================================================
// Configuration Loading
// ============================================================================

bool test_runner::load_config() {
  // Load build directory from config (same as main build uses)
  std::string build_dir_str = m_project_config.get_string("build.build_dir", "build");
  m_build_base_dir = m_project_dir / build_dir_str;

  // Load [test] section defaults
  m_test_config.directory = m_project_config.get_string("test.directory", "tests");
  m_test_config.default_timeout =
      static_cast<cforge_int_t>(m_project_config.get_int("test.timeout", 300));
  m_test_config.jobs =
      static_cast<cforge_int_t>(m_project_config.get_int("test.jobs", 0));
  m_test_config.auto_link_project =
      m_project_config.get_bool("test.auto_link_project", true);
  m_test_config.discovery_mode =
      m_project_config.get_string("test.discovery", "both");

  // Parse output style
  std::string output_style = m_project_config.get_string("test.output_style", "cargo");
  m_test_config.cargo_style_output = (output_style != "native");

  // Parse default framework
  std::string fw_str = m_project_config.get_string("test.framework", "auto");
  m_test_config.default_framework = string_to_test_framework(fw_str);

  // Load framework-specific configs
  load_framework_config(test_framework::GTest, "test.gtest");
  load_framework_config(test_framework::Catch2, "test.catch2");
  load_framework_config(test_framework::Doctest, "test.doctest");
  load_framework_config(test_framework::BoostTest, "test.boost");

  return true;
}

void test_runner::load_framework_config(test_framework fw, const std::string &section) {
  if (!m_project_config.has_key(section)) {
    return;
  }

  test_config::FrameworkConfig fc;
  fc.fetch = m_project_config.get_bool(section + ".fetch", true);
  fc.version = m_project_config.get_string(section + ".version", "");

  // Load additional options from the section
  auto opts = m_project_config.get_string_map(section);
  for (const auto &[key, val] : opts) {
    if (key != "fetch" && key != "version") {
      fc.options[key] = val;
    }
  }

  m_test_config.framework_configs[fw] = fc;
}

fs::path test_runner::get_test_gen_dir(const std::string &target_name) const {
  // Fallback if load_config() wasn't called
  if (m_build_base_dir.empty()) {
    return m_project_dir / "build" / "tests" / target_name;
  }
  return m_build_base_dir / "tests" / target_name;
}

fs::path test_runner::get_test_build_dir(const std::string &target_name) const {
  return get_test_gen_dir(target_name) / "build";
}

// ============================================================================
// Target Discovery
// ============================================================================

std::vector<test_target> test_runner::discover_targets() {
  std::vector<test_target> targets;

  // Load explicit targets first (always)
  if (m_test_config.discovery_mode == "explicit" ||
      m_test_config.discovery_mode == "both") {
    auto explicit_targets = load_explicit_targets();
    targets.insert(targets.end(), explicit_targets.begin(), explicit_targets.end());
  }

  // Auto-discover if requested
  if (m_test_config.discovery_mode == "auto" ||
      m_test_config.discovery_mode == "both") {
    auto auto_targets = auto_discover_targets();

    // Merge auto-discovered targets, avoiding duplicates
    for (auto &target : auto_targets) {
      bool exists = false;
      for (const auto &existing : targets) {
        if (existing.name == target.name) {
          exists = true;
          break;
        }
      }
      if (!exists) {
        targets.push_back(std::move(target));
      }
    }
  }

  // Store in config
  m_test_config.targets = targets;
  return targets;
}

std::vector<test_target> test_runner::load_explicit_targets() {
  std::vector<test_target> targets;

  auto target_tables = m_project_config.get_table_array("test.targets");
  for (const auto &table : target_tables) {
    test_target target;
    target.name = table.get_string("name", "");
    if (target.name.empty()) {
      logger::print_warning("[[test.targets]] entry missing 'name', skipping");
      continue;
    }

    target.sources = table.get_string_array("sources");
    target.dependencies = table.get_string_array("dependencies");
    target.defines = table.get_string_array("defines");
    target.includes = table.get_string_array("includes");
    target.timeout_seconds =
        static_cast<cforge_int_t>(table.get_int("timeout", m_test_config.default_timeout));
    target.enabled = table.get_bool("enabled", true);

    // Parse framework
    std::string fw_str = table.get_string("framework", "auto");
    target.framework = string_to_test_framework(fw_str);

    // Expand source globs
    target.source_files = expand_globs(target.sources, m_project_dir);

    // Detect framework from sources if auto
    if (target.framework == test_framework::Auto && !target.source_files.empty()) {
      target.framework = detect_framework(target.source_files.front());
    }

    if (!target.source_files.empty()) {
      targets.push_back(std::move(target));
    } else {
      logger::print_warning("Test target '" + target.name + "' has no source files");
    }
  }

  return targets;
}

std::vector<test_target> test_runner::auto_discover_targets() {
  std::vector<test_target> targets;

  fs::path test_dir = m_project_dir / m_test_config.directory;
  logger::print_verbose("Looking for tests in: " + test_dir.string());
  if (!fs::exists(test_dir) || !fs::is_directory(test_dir)) {
    logger::print_verbose("Test directory does not exist: " + test_dir.string());
    return targets;
  }

  // Look for test source files
  std::vector<fs::path> test_files;
  for (const auto &entry : fs::recursive_directory_iterator(test_dir)) {
    if (!entry.is_regular_file()) continue;

    auto ext = entry.path().extension().string();
    if (ext == ".cpp" || ext == ".cxx" || ext == ".cc") {
      test_files.push_back(entry.path());
    }
  }

  if (test_files.empty()) {
    logger::print_verbose("No test source files found in " + test_dir.string());
    return targets;
  }

  logger::print_verbose("Found " + std::to_string(test_files.size()) + " test source files");

  // Group files by directory to create targets
  std::map<fs::path, std::vector<fs::path>> files_by_dir;
  for (const auto &file : test_files) {
    fs::path rel = fs::relative(file.parent_path(), test_dir);
    files_by_dir[rel].push_back(file);
  }

  // Create one target per directory (or single target for flat structure)
  // Note: fs::relative() returns "." on Windows but empty path on some Linux systems
  auto first_rel = files_by_dir.begin()->first;
  bool is_flat = files_by_dir.size() == 1 &&
                 (first_rel == "." || first_rel.empty() || first_rel == test_dir.filename());
  if (is_flat) {
    // Flat structure - single target
    test_target target;
    target.name = "tests";
    target.source_files = test_files;
    target.timeout_seconds = m_test_config.default_timeout;

    // Detect framework from first file
    target.framework = detect_framework(test_files.front());

    targets.push_back(std::move(target));
  } else {
    // Multiple directories - one target per directory
    for (const auto &[dir, files] : files_by_dir) {
      test_target target;
      target.name = "test_" + dir.string();
      // Replace path separators with underscores
      std::replace(target.name.begin(), target.name.end(), '/', '_');
      std::replace(target.name.begin(), target.name.end(), '\\', '_');

      target.source_files = files;
      target.timeout_seconds = m_test_config.default_timeout;
      target.framework = detect_framework(files.front());

      targets.push_back(std::move(target));
    }
  }

  return targets;
}

std::vector<fs::path> test_runner::expand_globs(
    const std::vector<std::string> &patterns, const fs::path &base_dir) {
  std::vector<fs::path> result;

  for (const auto &pattern : patterns) {
    // Simple glob expansion - handle ** and *
    fs::path pattern_path = base_dir / pattern;
    fs::path search_dir = pattern_path.parent_path();
    std::string filename_pattern = pattern_path.filename().string();

    // Convert glob to regex
    std::string regex_pattern = filename_pattern;
    // Escape regex special chars except * and ?
    std::string escaped;
    for (char c : regex_pattern) {
      if (c == '*') {
        escaped += ".*";
      } else if (c == '?') {
        escaped += ".";
      } else if (std::string("^$.|()[]{}+\\").find(c) != std::string::npos) {
        escaped += '\\';
        escaped += c;
      } else {
        escaped += c;
      }
    }

    std::regex file_regex(escaped, std::regex::icase);

    // Handle ** in directory path
    bool recursive = pattern.find("**") != std::string::npos;

    if (!fs::exists(search_dir)) {
      continue;
    }

    auto iterate = [&](auto &iterator) {
      for (const auto &entry : iterator) {
        if (!entry.is_regular_file()) continue;

        std::string filename = entry.path().filename().string();
        if (std::regex_match(filename, file_regex)) {
          result.push_back(entry.path());
        }
      }
    };

    if (recursive) {
      fs::recursive_directory_iterator iter(search_dir);
      iterate(iter);
    } else {
      fs::directory_iterator iter(search_dir);
      iterate(iter);
    }
  }

  return result;
}

// ============================================================================
// Framework Detection
// ============================================================================

test_framework test_runner::detect_framework(const fs::path &source_file) {
  std::ifstream file(source_file);
  if (!file) {
    return m_test_config.default_framework;
  }

  std::ostringstream ss;
  ss << file.rdbuf();
  std::string content = ss.str();

  // Try each adapter
  std::vector<test_framework> frameworks = {
    test_framework::GTest,
    test_framework::Catch2,
    test_framework::Doctest,
    test_framework::BoostTest,
    test_framework::Builtin
  };

  for (auto fw : frameworks) {
    auto adapter = get_adapter(fw);
    if (adapter && adapter->detect_from_source(content)) {
      return fw;
    }
  }

  return m_test_config.default_framework;
}

i_test_framework_adapter *test_runner::get_adapter(test_framework fw) {
  if (fw == test_framework::Auto) {
    fw = test_framework::Builtin;
  }

  auto it = m_adapters.find(fw);
  if (it != m_adapters.end()) {
    return it->second.get();
  }

  auto adapter = create_adapter(fw);
  auto *ptr = adapter.get();
  m_adapters[fw] = std::move(adapter);
  return ptr;
}

// ============================================================================
// CMake Generation
// ============================================================================

fs::path test_runner::write_builtin_header(const fs::path &gen_dir) {
  fs::path inc_dir = gen_dir / "cforge_includes";
  std::error_code ec;
  fs::create_directories(inc_dir, ec);

  fs::path header_path = inc_dir / "test_framework.h";
  std::ofstream out(header_path);
  if (!out) {
    logger::print_warning("Could not write generated header: " + header_path.string());
    return {};
  }
  out << get_builtin_test_framework_header();
  return inc_dir;
}

fs::path test_runner::generate_main_if_needed(const test_target &target,
                                              const fs::path &gen_dir) {
  // Only auto-generate for the cforge builtin framework. Other frameworks
  // (GTest's gtest_main, Catch2WithMain, doctest's _IMPLEMENT) handle this
  // themselves.
  if (target.framework != test_framework::Builtin &&
      target.framework != test_framework::Auto) {
    return {};
  }

  // Detect a user-defined main(...) in any source file. Use a regex that
  // ignores comments only loosely — false negatives just generate an extra
  // main and produce a clear linker error, which is fine.
  static const std::regex main_re(R"(\bint\s+main\s*\()");
  for (const auto &src : target.source_files) {
    std::string contents = read_file_to_string(src);
    if (std::regex_search(contents, main_re)) {
      return {}; // user has their own main
    }
  }

  fs::path main_path = gen_dir / "cforge_test_main.cpp";
  std::ofstream out(main_path);
  if (!out) {
    logger::print_warning("Could not write generated test main: " + main_path.string());
    return {};
  }
  out << "// Auto-generated by cforge — runs all auto-registered TEST() macros.\n"
         "#include \"test_framework.h\"\n"
         "int main(int argc, char** argv) { return cf_run_tests(argc, argv); }\n";
  return main_path;
}

bool test_runner::generate_test_cmake(const test_target &target) {
  // Use configured build directory for test outputs
  fs::path gen_dir = get_test_gen_dir(target.name);
  logger::print_verbose("Test CMake dir: " + gen_dir.string());
  fs::create_directories(gen_dir);

  // Drop the cforge builtin header into the build dir so users can
  // #include "test_framework.h" without ever copying a file into their source.
  fs::path generated_inc_dir = write_builtin_header(gen_dir);

  // Auto-generate a tiny main() if the user hasn't written one and the target
  // uses the builtin framework. Auto-registration via TEST() does the rest.
  fs::path generated_main = generate_main_if_needed(target, gen_dir);

  fs::path cmake_file = gen_dir / "CMakeLists.txt";
  std::ofstream out(cmake_file);
  if (!out) {
    m_error = "FAILED to create " + cmake_file.string();
    return false;
  }

  // Get adapter for framework
  auto *adapter = get_adapter(target.framework);
  if (!adapter) {
    m_error = "No adapter for framework: " + test_framework_to_string(target.framework);
    return false;
  }

  // Get framework config
  test_config::FrameworkConfig fw_config;
  auto it = m_test_config.framework_configs.find(target.framework);
  if (it != m_test_config.framework_configs.end()) {
    fw_config = it->second;
  }

  out << "cmake_minimum_required(VERSION 3.15)\n"
      << "project(" << target.name << "_test CXX C)\n\n"
      << "enable_testing()\n\n";

  // Set C++ standard from project config
  std::string cxx_std = m_project_config.get_string("project.cpp_standard", "17");
  out << "set(CMAKE_CXX_STANDARD " << cxx_std << ")\n"
      << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";

  // Configure project dependencies via FetchContent (reads from cforge.toml)
  configure_index_dependencies_fetchcontent_phase1(m_project_dir, m_project_config, out);

  // Add framework setup
  std::string fw_setup = adapter->generate_cmake_setup(fw_config);
  if (!fw_setup.empty()) {
    out << fw_setup << "\n";
  }

  // Source files
  out << "# Test sources\n"
      << "set(TEST_SOURCES\n";
  for (const auto &src : target.source_files) {
    out << "  \"" << to_cmake_path(src) << "\"\n";
  }
  if (!generated_main.empty()) {
    out << "  \"" << to_cmake_path(generated_main) << "\"\n";
  }
  out << ")\n\n";

  // Create executable
  out << "add_executable(${PROJECT_NAME} ${TEST_SOURCES})\n\n";

  // Include directories
  out << "target_include_directories(${PROJECT_NAME} PRIVATE\n"
      << "  \"" << to_cmake_path(m_project_dir / "include") << "\"\n"
      << "  \"" << to_cmake_path(m_project_dir / "src") << "\"\n"
      << "  \"" << to_cmake_path(m_project_dir / m_test_config.directory) << "\"\n";
  if (!generated_inc_dir.empty()) {
    out << "  \"" << to_cmake_path(generated_inc_dir) << "\"\n";
  }
  for (const auto &inc : target.includes) {
    out << "  \"" << to_cmake_path(m_project_dir / inc) << "\"\n";
  }
  out << ")\n\n";

  // Link project dependencies (reads from cforge.toml)
  configure_index_dependencies_fetchcontent_phase2(m_project_dir, m_project_config, out);

  // Link framework and additional targets
  out << "target_link_libraries(${PROJECT_NAME} PRIVATE\n";

  // Framework target
  std::string cmake_target = adapter->get_cmake_target();
  if (!cmake_target.empty()) {
    out << "  " << cmake_target << "\n";
  }

  // Auto-link project if applicable
  if (should_auto_link_project()) {
    std::string project_target = get_project_link_target();
    if (!project_target.empty()) {
      out << "  " << project_target << "\n";
    }
  }

  // User dependencies
  for (const auto &dep : target.dependencies) {
    out << "  " << dep << "\n";
  }
  out << ")\n\n";

  // Defines
  if (!target.defines.empty()) {
    out << "target_compile_definitions(${PROJECT_NAME} PRIVATE\n";
    for (const auto &def : target.defines) {
      out << "  " << def << "\n";
    }
    out << ")\n\n";
  }

  // CTest integration — for every framework. GTest/Catch2 use their CMake
  // helpers for per-test discovery; for the others we register the binary as
  // a single test so plain `ctest` still works.
  if (target.framework == test_framework::GTest) {
    out << "include(GoogleTest)\n"
        << "gtest_discover_tests(${PROJECT_NAME})\n";
  } else if (target.framework == test_framework::Catch2) {
    out << "include(Catch)\n"
        << "catch_discover_tests(${PROJECT_NAME})\n";
  } else {
    out << "add_test(NAME " << target.name << " COMMAND ${PROJECT_NAME})\n";
    if (target.timeout_seconds > 0) {
      out << "set_tests_properties(" << target.name << " PROPERTIES TIMEOUT "
          << target.timeout_seconds << ")\n";
    }
  }

  return true;
}

bool test_runner::should_auto_link_project() const {
  if (!m_test_config.auto_link_project) {
    return false;
  }

  std::string type = m_project_config.get_string("project.binary_type", "executable");
  return (type == "library" || type == "static_library" ||
          type == "shared_library" || type == "static" || type == "shared");
}

std::string test_runner::get_project_link_target() const {
  std::string name = m_project_config.get_string("project.name", "");
  if (name.empty()) {
    return "";
  }
  return name;
}

// ============================================================================
// Building
// ============================================================================

bool test_runner::configure_cmake(const test_target &target,
                                  const std::string &build_config) {
  fs::path gen_dir = get_test_gen_dir(target.name);
  fs::path build_dir = get_test_build_dir(target.name);

  // Ensure build directory exists
  fs::create_directories(build_dir);

  std::vector<std::string> args = {
    "-S", to_cmake_path(gen_dir),
    "-B", to_cmake_path(build_dir),
    "-DCMAKE_BUILD_TYPE=" + build_config
  };

#ifdef _WIN32
  // Use same generator as main project if specified
  std::string generator = m_project_config.get_string("build.generator", "");
  if (!generator.empty()) {
    args.push_back("-G");
    args.push_back(generator);
  }
#endif

  // Use execute_process directly for cleaner error handling
  auto result = execute_process("cmake", args, m_project_dir.string(), nullptr, nullptr, 120);
  if (!result.success) {
    // Store error for later reporting
    m_error = "CMake configuration failed";
    logger::print_error("FAILED to configure " + target.name);
    if (!result.stderr_output.empty()) {
      logger::print_plain(result.stderr_output);
    }
    if (!result.stdout_output.empty()) {
      logger::print_plain(result.stdout_output);
    }
  }
  return result.success;
}

bool test_runner::build_target(const test_target &target,
                               const std::string &build_config) {
  fs::path build_dir = get_test_build_dir(target.name);

  std::vector<std::string> args = {
    "--build", to_cmake_path(build_dir),
    "--config", build_config
  };

  // Stream output live so compile errors are visible (cmake --build can exit 0
  // even when MSBuild reports errors — we also do a post-build exe check).
  auto result = execute_process(
      "cmake", args, m_project_dir.string(),
      [](const std::string &line) { logger::print_plain(line); },
      [](const std::string &line) { logger::print_error(line); },
      300);

  if (!result.success) {
    m_error = "Build failed";
    logger::print_error("FAILED to build " + target.name);
    return false;
  }

  // Detect the silent-failure case: cmake reports success but no executable
  // was produced. Treat as a build error rather than letting it surface later
  // as a confusing "executable not found".
  fs::path exe = find_test_executable(target, build_config);
  if (exe.empty()) {
    m_error = "Build reported success but no executable was produced for " +
              target.name + " (likely a compile error — see output above).";
    logger::print_error(m_error);
    return false;
  }
  return true;
}

bool test_runner::build_tests(const std::string &config, [[maybe_unused]] bool verbose) {
  // Discover targets if not already done
  if (m_test_config.targets.empty()) {
    discover_targets();
  }

  bool all_success = true;
  for (const auto &target : m_test_config.targets) {
    if (!target.enabled) continue;

    logger::print_action("Building", "test target: " + target.name);

    // Generate CMakeLists.txt
    if (!generate_test_cmake(target)) {
      logger::print_error("FAILED to generate CMake for " + target.name);
      all_success = false;
      continue;
    }

    // Configure (error printed inside)
    if (!configure_cmake(target, config)) {
      all_success = false;
      continue;
    }

    // Build (error printed inside)
    if (!build_target(target, config)) {
      all_success = false;
      continue;
    }
  }

  return all_success;
}

// ============================================================================
// Test Execution
// ============================================================================

fs::path test_runner::find_test_executable(const test_target &target,
                                           const std::string &build_config) {
  fs::path build_dir = get_test_build_dir(target.name);

  // Try the well-known paths first (fast path), then fall back to a bounded
  // recursive walk so we cope with whatever directory layout the configured
  // CMake generator produces.
  std::vector<fs::path> fast_candidates = {
    build_dir / (target.name + "_test.exe"),
    build_dir / (target.name + "_test"),
    build_dir / build_config / (target.name + "_test.exe"),
    build_dir / build_config / (target.name + "_test"),
    build_dir / "Debug" / (target.name + "_test.exe"),
    build_dir / "Debug" / (target.name + "_test"),
    build_dir / "Release" / (target.name + "_test.exe"),
    build_dir / "Release" / (target.name + "_test"),
  };
  for (const auto &p : fast_candidates) {
    if (fs::exists(p)) return p;
  }

  // Fall back to a recursive search keyed on the CMake project name. The
  // CMakeLists we generate uses `target.name + "_test"` as the project name,
  // and CMake names the executable after the project unless overridden, so
  // this is a stable signal across generators.
  std::vector<std::string> name_candidates = {
    target.name + "_test",
    target.name,
  };
  return find_executable_in_dir(build_dir, name_candidates);
}

std::vector<test_result> test_runner::run_target(const test_target &target,
                                                const test_run_options &options) {
  std::vector<test_result> results;

  fs::path exe = find_test_executable(target, options.build_config);
  if (exe.empty()) {
    test_result error_result;
    error_result.name = target.name;
    error_result.status = test_status::FAILED;
    error_result.failure_message = "Test executable not found";
    results.push_back(error_result);
    return results;
  }

  // Get adapter
  auto *adapter = get_adapter(target.framework);
  if (!adapter) {
    test_result error_result;
    error_result.name = target.name;
    error_result.status = test_status::FAILED;
    error_result.failure_message = "No adapter for framework";
    results.push_back(error_result);
    return results;
  }

  // Build command arguments
  std::vector<std::string> args;

  if (!options.filter.empty()) {
    auto filter_args = adapter->get_filter_args(options.filter);
    args.insert(args.end(), filter_args.begin(), filter_args.end());
  }

  if (options.native_output || options.verbose) {
    auto verbose_args = adapter->get_verbose_args();
    args.insert(args.end(), verbose_args.begin(), verbose_args.end());
  }

  // Execute test
  cforge_int_t timeout = options.timeout_override > 0 ? options.timeout_override : target.timeout_seconds;

  auto proc_result = execute_process(exe.string(), args,
                                      m_project_dir.string(),
                                      nullptr, nullptr, timeout);

  // Parse output — strip ANSI escape codes first so colored test output still
  // matches the [RUN]/[PASS]/[FAIL] regexes the adapters use.
  std::string combined_output =
      strip_ansi(proc_result.stdout_output + proc_result.stderr_output);

  if (options.native_output) {
    // Just print native output, create summary result
    logger::print_plain(combined_output);

    test_result summary;
    summary.name = target.name;
    summary.status = proc_result.success ? test_status::PASSED : test_status::FAILED;
    results.push_back(summary);
  } else {
    // Parse output into individual results
    results = adapter->parse_output(combined_output);

    // If parsing returned nothing, create a summary result
    if (results.empty()) {
      test_result summary;
      summary.name = target.name;
      summary.status = proc_result.success ? test_status::PASSED : test_status::FAILED;
      if (!proc_result.success) {
        summary.failure_message = "Test execution failed";
        summary.notes.push_back("Exit code: " + std::to_string(proc_result.exit_code));
      }
      results.push_back(summary);
    }
  }

  return results;
}

test_summary test_runner::run_tests(const test_run_options &options) {
  test_summary summary;
  m_results.clear();

  auto start_time = std::chrono::steady_clock::now();

  // Build if needed
  if (!options.no_build) {
    if (!build_tests(options.build_config, options.verbose)) {
      summary.failed = 1;
      summary.total = 1;
      return summary;
    }
  }

  // Run each target
  for (const auto &target : m_test_config.targets) {
    if (!target.enabled) continue;

    auto results = run_target(target, options);
    m_results.insert(m_results.end(), results.begin(), results.end());
  }

  // Calculate summary
  for (const auto &result : m_results) {
    summary.total++;
    switch (result.status) {
      case test_status::PASSED:
        summary.passed++;
        break;
      case test_status::FAILED:
        summary.failed++;
        summary.failed_tests.push_back(result.name);
        break;
      case test_status::SKIPPED:
        summary.skipped++;
        break;
      case test_status::TIMEOUT:
        summary.timeout++;
        summary.failed_tests.push_back(result.name + " (timeout)");
        break;
      default:
        break;
    }
    summary.total_duration += result.duration;
  }

  auto end_time = std::chrono::steady_clock::now();
  summary.total_duration = std::chrono::duration_cast<std::chrono::milliseconds>(
      end_time - start_time);

  return summary;
}

std::vector<std::string> test_runner::list_tests() {
  std::vector<std::string> all_tests;

  // Make sure targets are discovered
  if (m_test_config.targets.empty()) {
    discover_targets();
  }

  // For each target, try to get test list
  for (const auto &target : m_test_config.targets) {
    if (!target.enabled) continue;

    fs::path exe = find_test_executable(target, "Debug");
    if (exe.empty()) {
      // Not built yet - just list target name
      all_tests.push_back("[" + target.name + "] (not built)");
      continue;
    }

    auto *adapter = get_adapter(target.framework);
    if (!adapter) continue;

    auto list_args = adapter->get_list_args();
    auto proc_result = execute_process(exe.string(), list_args,
                                        m_project_dir.string(),
                                        nullptr, nullptr, 30);

    if (proc_result.success) {
      auto tests = adapter->parse_test_list(proc_result.stdout_output);
      for (const auto &test : tests) {
        all_tests.push_back(target.name + "::" + test);
      }
    } else {
      all_tests.push_back("[" + target.name + "] (list failed)");
    }
  }

  return all_tests;
}

} // namespace cforge
